# Generated by Django 5.1.3 on 2024-11-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_requisitionapprovallog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionapprovallog',
            name='approved_quantity',
        ),
    ]
