# Generated by Django 5.1.3 on 2024-11-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_requisitionapprovallog_approved_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
