# Generated by Django 5.1.3 on 2024-11-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_requisition_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='requisition_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
